### ISSUE TITLE
Consider using Caddy webserver which will autoget SSL certs for auto HTTPS

### ISSUE THREAD

**Issue by vRobM** [proofrock/pupcloud#12]
This will solve a lot of issues with security and relieve rev-proxy setups.

**Comment by proofrock** [comment]
Thanks. I don't think Caddy can be embedded (I may be wrong). Even if it could be, I am quite doubtful. It's easy enough to use Caddy on its own as a reverse proxy, as documented [here](https://germ.gitbook.io/pupcloud/guides/reverse-proxy); embedding it would limit the possibilities. For example, you couldn't use a different proxy (e.g. NGINX), you couldn't protect more than one server, and in order to have it run on ports 80/443 you would need to run pupcloud as root, and I really don't think it would be good. It's much better to keep the reverse proxy separate, IMHO. 

I'll leave this open for a while, for reference, and to possibly gather further feedback.

**Comment by vRobM** [comment]
Well, it's a standalone binary and it's easy to use as a webserver that will get certs on any port.

Pick any other option that does those things and there will be much rejoicing ;-)

**Comment by proofrock** [comment]
Thanks, I'll consider it. https://github.com/foomo/simplecert/ seems to be a way. Still not convinced that it's a good idea ;-)

**Comment by proofrock** [comment]
Sorry, I won't do it. The possibility is there, of course, but it would add a ton of complexity (in terms of code, maintenance and commandline args) for an use case that is quite simple to address "outside" pupcloud (`caddy reverse-proxy --from pupcloud.com --to localhost:17178`).

Doing so gives you control over which version of Caddy to use, with all the latest security fixes; peace of mind that those security fixes come directly from upstream, without passing through "me"; allow you to configure more than one service; and in general, separation of concerns is a good thing. 

But, thanks for the idea, the discussion and for taking the time to report it!
