### ISSUE TITLE
Link in wiki to Roadmap links to itself, not the Roadmap

### ISSUE THREAD

**Issue by marioscube** [proofrock/pupcloud#44]
See title
![Screenshot 2022-05-11 at 23 17 41](https://user-images.githubusercontent.com/20281601/167950071-42c367e3-eb07-40a5-bbad-049ea3999c19.png)

I like most of the items in the Roadmap.

Please remember, you wrote [pupcloud] "It is an exercise in minimalism".

I fear that when you integrate all of the items in the Roadmap into pupcloud it no longer will be no longer "minimal" in size, code, functionality (do we want another Nextcloud?) and maximal in speed.

Bu in the end, it's YOUR project. Only you can decide where to go with pupcloud.

So far, thank you for pupcloud!

If we want to discuss pupclouod, we cannot contain our enthusiasm, where should we do that?
Maybe you could open a topic in "Discussions"?

**Comment by DarrenPIngram** [comment]
Well maybe the core, out-of-a-box runtime can be "minimal" but have
optional elements.

I believe the general requests so far still don't make another Owncloud or
the like, but complement the simplicity and usability of the application.

Now, the developer has the difficult choice of what he CAN add and what he
CHOOSES to add. The rest of us can be enthusiastic around what seems to be
a great base and seek to enhance this rather than totally change it. Just
my two euro cents :)

**Comment by DarrenPIngram** [comment]
For my part not Discord pls -  yet another thing to check. Git+email alert is fine. More structured for you too.


—- 
Via iPad. Hopefully with not too many typos.
