### ISSUE TITLE
If a share link is expired, it asks for the password even if it's not required

### ISSUE THREAD

**Issue by proofrock** [proofrock/pupcloud#47]
It seems to get confused by the `499` error. I have to investigate a bit more.

**Comment by marioscube** [comment]
I have seen that error when I was experimenting with reverse proxy.

it looks like webserver error.

**Comment by marioscube** [comment]
OK.

Regrettably apache2 cannot handle error 499.

**Comment by proofrock** [comment]
Ouch. This hash always been a sort of hack, and it should be at least documented, I know. But what cannot apache do? I think if you setup a password, connect via reverse proxy, and put in the wrong password, it asks you again for it, and if you put the right one it allows you to pass, right? If not, I think you would have reported the case. So, it actually seems to pass 499 correctly...

**Comment by marioscube** [comment]
To clarify. with apache "cannot handle error 499" I meant that if apache gets an error 499 from the reverse proxy apache cannot handle it with "ErrorDocument 499".

This error 499 was probably because I misconfigured apache in some way.

I was working on:
- connect to pupcloud through a domain name on http
- the rewrite to http (letsencrypt)
- reverse proxy to http://<local IP>:17178
- make sure that I can only get pupcloud from this domain name end not anything else that might be on the server.
Somewhere in the process of setting this up I get an error 499.  So I tried another setup and now it sorta works like i want it to (95% solution). Nothing to do with pupcloud.

**Comment by proofrock** [comment]
The 499 is totally correct; if you set up a password, the first time it connects pupcloud gives 499 (=my custom error to say "password required"), the rev proxy must let it pass so that the web part can understand that a password is needed. If you then put the password, the second call should give 200.

**Comment by proofrock** [comment]
> make sure that I can only get pupcloud from this domain name

In due time, I could add a CORS check that HOST matches a string passed in config, like I do [for my other pet project](https://germ.gitbook.io/ws4sqlite/documentation/configuration-file#corsorigin).

**Comment by marioscube** [comment]
499 mystery solved (for me). I do not log this and other message(s). If it works I  do not need megabytes of logs.

What I wanted is that when someone messes with the http(s)://url in the browser it still always redirects to pupcloud.
Handy for shares to others.

**Comment by proofrock** [comment]
@marioscube Can I close this?
